import { z } from "zod";

/**
 * Runtime schema for catalog data. The catalog is generated by a script and
 * baked to JSON, so we parse it through this schema at load time — bad data
 * fails loudly at the boundary instead of producing `undefined`s deep in the UI.
 */
export const reviewSchema = z.object({
  rating: z.number(),
  comment: z.string(),
  reviewerName: z.string(),
  date: z.string(),
});

export const colorSchema = z.object({
  name: z.string(),
  hex: z.string(),
});

export const categorySchema = z.enum([
  "shirts",
  "tops",
  "dresses",
  "shoes",
  "bags",
  "watches",
  "accessories",
]);

export const sizeSchema = z.enum(["XS", "S", "M", "L", "XL", "XXL"]);

export const productSchema = z.object({
  id: z.string(),
  slug: z.string(),
  name: z.string(),
  description: z.string(),
  details: z.array(z.string()),
  price: z.number().int().nonnegative(),
  compareAtPrice: z.number().int().nonnegative().optional(),
  category: categorySchema,
  collection: z.string(),
  sizes: z.array(sizeSchema),
  colors: z.array(colorSchema),
  images: z.array(z.string()),
  tags: z.array(z.string()),
  inStock: z.boolean(),
  featured: z.boolean().optional(),
  newArrival: z.boolean().optional(),
  rating: z.number().optional(),
  reviewCount: z.number().optional(),
  reviews: z.array(reviewSchema).optional(),
  brand: z.string().nullable().optional(),
  stock: z.number().optional(),
});

export const catalogSchema = z.array(productSchema);
